{% set name = "signac" %}
{% set version = "1.4.0" %}
{% set sha256 = "c7d4635625911c17666950027228945f20441ffe2ec145fd84c728431d037b45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/signac/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - signac = signac.__main__:main

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - bcrypt
    - deprecation >=2
    - filelock >=3.0,<4
    - packaging >=15.0
    - passlib
    - pymongo >=3
    - python >=3.5
    - tqdm >=4.10.0

test:
  imports:
    - signac
    - signac.common
    - signac.contrib
    - signac.core
    - signac.db

about:
  home: https://signac.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Manage large and heterogeneous data spaces on the file system.'
  description: |
    The signac framework helps users manage and scale file-based workflows,
    facilitating data reuse, sharing, and reproducibility. It provides a simple
    and robust data model to create a well-defined indexable storage layout for
    data and metadata. This makes it easier to operate on large data spaces,
    streamlines post-processing and analysis and makes data collectively
    accessible.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/signac

extra:
  recipe-maintainers:
    - bdice
    - csadorf
    - mikemhenry
    - vyasr
