{% set name = "signac" %}
{% set version = "1.1.0" %}
{% set sha256 = "658dfc5f3912044de24601f3764cbe7f239f5c1343c71ff904b6cf4c98ae5172" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/signac/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - signac = signac.__main__:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pymongo >=3
    - passlib
    - bcrypt

test:
  imports:
    - signac
    - signac.common
    - signac.contrib
    - signac.core
    - signac.db

about:
  home: https://signac.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Simple, extensible data management framework.'
  description: |
    The signac framework aids in the management of large and heterogeneous
    data spaces. It provides a simple and robust data model to create a
    well-defined indexable storage layout for data and metadata.
    This makes it easier to operate on large data spaces, streamlines
    post-processing and analysis and makes data collectively accessible.
    The implementation is in pure python and tested for versions 2.7.x and
    3.4+. There are no hard dependencies to allow painless transition into
    various environments, some extra features are available via optional
    dependencies.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/signac

extra:
  recipe-maintainers:
    - csadorf
