{% set name = "signac" %}
{% set version = "1.3.0" %}
{% set sha256 = "af5aa9e03ed976d1f2ee950b50b5a8907b31540254b79e6126ba5c7891fcf01b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/signac/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - signac = signac.__main__:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - bcrypt
    - deprecation >=2
    - filelock >=3.0,==3.*
    - packaging >=15.0
    - passlib
    - pymongo >=3
    - python

test:
  imports:
    - signac
    - signac.common
    - signac.contrib
    - signac.core
    - signac.db

about:
  home: https://signac.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Simple, extensible data management framework.'
  description: |
    The signac framework aids in the management of large and heterogeneous
    data spaces. It provides a simple and robust data model to create a
    well-defined indexable storage layout for data and metadata.
    This makes it easier to operate on large data spaces, streamlines
    post-processing and analysis and makes data collectively accessible.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/signac

extra:
  recipe-maintainers:
    - bdice
    - csadorf
    - mikemhenry
    - vyasr
