travis:
  secure:
    BINSTAR_TOKEN: qGZK3HaEvg8P2RV2u21A5eAS/CSZbpjFQdOOKSZUvG6kfx3udxe+u2ha1rKb1dn8VwnoTcCQagpXXFaWPsCnEoqpVtKIBnnG0xdWOgW6e6IoTlah13jxUBAuPfSnw4DApv3sQph9pMcV6NbJAV5HLgHrASx/q9qzDY8xYGnZXgTXi3RMioR1Zv4f2IpZX0KjNr/MbzhTZ8oWClXfbOZyXh13C6YphmJXNhQK06pgH0C76gHTjDA5fB7rC409GAvqZn5wjILxqcZP9NXsyYjzK3fjYOQi8vkR0XEzSzsXbGI7Ft/uhrSzhojMosqoTdQ4jspujOtdnbMNiheN+CQcGk+rCeXOXua1sgaainwmL6KHnfKLBO7VgOpNaQnwaHBWSNknEaCCdNifWT4EUsbd2jKYznxTpvayoh4UMbWZ73UDNLYWonjZLFqeMOEDEGBqyHt19nCPkvK0Q9MpXtUi+I09g0xZxKCAy7lsjyoo2LeaVi8xFj32xir4+yguobTBKDjFEQxBWEVC3c8xSjAVIY4xOq+kVEeBA1yJDjLA2EOQ5d6HETfBquHgjk/cLBGh6Lrl9E4NuU+XmuhxKrB00r6kNC/f8lF3ABU+9ZMEqpdvc23MjDXh3dNv7Xru43KsrPYa1wT+XscpPfoiQgMkQ5I4xXI6wh0i8IUZJTnYH1c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
