travis:
  secure:
    BINSTAR_TOKEN: AXLWxKAuS/DS81G4iPrkc4sIHd6FzMjc7Sw7aRRbsguSPEv+cgvpzv8NhCSCZyL+OM7vsqBeoTlFI21NFcKcVczCN1oJKyqvusp6TZhSC8DTSYZwKm/SySneL0lln6oLt1Kl/7g9UKlvoWH8wGYn4sE+y5s6p9N1rHXeqd4RZkE9zrowxFndb4ErdKbksfmJg9f7U1V9bZik+AqOIbMgKyT+U6zzSvCuFTHGogM+QdOsCbNe/m7AYP4DyPNpxf94+cOeM9LPHfMuRPakPG5ZLWEzk90YMPmy4J+XLR6TrUkdg+sSiqR2PmRSONBb0OOgwDvVm9GUZakg2ephqFg0PtjHUtolzrAcbC2kIGa1apj7+3q0qbmNTKrC2GgaK88sdZtqDlQV7mQt1yGrqjTAWq7Ba/4X1ycEfcahOryK7gejsKxvnARSED/DUhpoZFlNantAvpKUwnEp/yNfOmwrxXvk8U4wZea9bB8dyoLVnMgOku0df3pgOYXOuTNSoblt6A6F4Ck+h9dtsnb0xu+HzPfBbXvDdias2mpgxBilCtWzluM4kFunCwU+QFrJu6SxkL1BsW2s0DrNAxVK1b/TmKyNPGmLSXV8iq+926O9fEVYWdh4AfKCmkIHqPffgfp7a4fOGQdhCUQUWoB7rnDI4XhafZ+XL1iaNQelcth/K78=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
