travis:
  secure:
    BINSTAR_TOKEN: HiAp489pzboFJtOp2/rdymJ9XWzPw3AVeiLmWuZRYM6TxUOOU7YVqIDM0cPAm877Xv2EYs1YkQ0hIkWZxZ+TSVuB7PMhoW4WHUUn3ci6EkgMX8hZSLEGTYclXegQqTK/rdofYfMLe61z+/g/2j+LBIvQjqnmxRcdXNah8kA1AApDXe4XTLqI0Lf5Mt3wPRhshUDJ24HhrHhDweonicaHee5+qYqg9irfYtiSF0KONU5rU9iPl/Fpv30JDubkns4hcGw5immvC47Xvdtsvf+feW6o9w7WHVZqaq4P6bSh+lew40kHV7Qlz3lUnMAM5YdEmJojpwtJ3Azm9yjmXt93i7a6/JzdACwIJSVDSfouQFpKvWp1bFHNaise0OtU7RMgeOoQhHtmHXLNdc4oOvHoNVAsRf360+qa+HNI1Gh29EhIRmRWx4xo9mPhjOKyKqy5S+F367rpjwXwMD+2qsaeyS94KDQSaCQX4xA7+x1PBE4WplyfroRAM1EaAdLrb5sQGUyR47FzL+zsReeEnmXUnSM09azA4sIQLa3gD++1L8CteUduHPhqals1Z1Qf32/EcrJeJ7leHZiwCj/yJmE+fHdpzmVxvo+UaUp6rj4ng4Xd7P80yBnQXHLj2WzftFiPzvD+NQIHGi41y2840+CpN+mPCMXKwUXrhwk6DaAh1Yk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
